# Site settings
title: cass.si #https://ftp.{{site.title}}/blah - incase of domain change
# permalink: none # prefix of post, i.e. .../2016-10-20-my-post
description: ""
baseurl: ""
url: "https://cass.si"
timezone: UTC+0
safe: false
future: true

permalink: /:categories/:title

ftp:
  root: "https://ftp.cass.si/www"
  assets: "https://ftp.cass.si/www/blog-assets"

# Build settings
markdown: kramdown
kramdown:
   input: GFM

# Syntax highlighter
highlighter: rouge
show_drafts: false

# Meta tag settings
license: MIT
author: cxss
e-mail: m (at) cxss (dot) si

#sed script replaces with true values from netlify
#build variables
recaptcha:
  sitekey: 
  secretkey: 

gitlab:
  username: cxss
  repo: cxss/site
  branch: master

plugins:
  - jekyll-youtube
  - jekyll-feed
  - jekyll-email-protect
  - jekyll-timeago
  - jekyll-twitter-plugin
  - jekyll-sitemap
  - liquid-md5

source: src
destination: _site
jekyll-bliss:
  build-folder: _build
  debug: false
  quiet: false
  delete-build-folder: true
  livereload: true
